replicaCount: 3
image:
  repository: 123456789012.dkr.ecr.us-west-2.amazonaws.com/my-service
  tag: latest
resources:
  limits:
    cpu: 500m
    memory: 512Mi
service:
  type: ClusterIP
  port: 80
env:
  ENV: prod
