replicaCount: 1
image:
  repository: 123456789012.dkr.ecr.us-west-2.amazonaws.com/my-service
  tag: latest
resources:
  limits:
    cpu: 100m
    memory: 128Mi
service:
  type: ClusterIP
  port: 80
env:
  ENV: dev
